services:
  postgres:
    image: postgres:16-alpine
    container_name: minishop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: minishop
      POSTGRES_USER: minishop_admin
      POSTGRES_PASSWORD: localdevpassword
    ports:
      - "5432:5432"
    volumes:
      - minishop_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minishop_admin -d minishop"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  minishop_pg_data:
